apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: grpc-echo
spec:
  host: grpc-echo
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: grpc-echo
spec:
  hosts:
  - grpc-echo
  http:
  - route:
    - destination:
        host: grpc-echo
        subset: v1
      weight: 50
    - destination:
        host: grpc-echo
        subset: v2
      weight: 50
    fault:
      abort:
        percentage:
          value: 50
        httpStatus: 500

